version: "3"

networks:
  default:
    external:
      name: ehh-world-dev-network

services:
  ehhioclient:
    container_name: ehhioclient
    build:
      context: ..
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    volumes:
      - ../:/usr/src/app
    command: npm run dev
